spring.application.name=Duetto
spring.datasource.url=${DB_URL: jdbc:mysql://localhost:3306/duetto}

spring.datasource.username=${DB_USERNAME: root}
spring.datasource.password=${DB_PASSWORD: root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud-name=dear7iqxa
cloudinary.api-key=832563836726966
cloudinary.api-secret=WfZbtKoB_mWF4_QEQ5klFpVGhDo